# This is a basic workflow to help you get started with Actions

name: CI Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request closed event but only for the "main" branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-on-success:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    uses: ./blank.yml
    needs: [build]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        if: ${{ github.event.number != null }}
        run: echo pr number ${{ github.event.number }}

      - name: Verify changes
        run: cat test.txt

      - name: Verify commit sha
        run: |
          export COMMIT_SHA=${GITHUB_SHA::7}
          echo $COMMIT_SHA
  deploy-always:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        if: ${{ github.event.number != null }}
        run: echo pr number ${{ github.event.number }}
