name: Deploy Azure functions

on:
  pull_request_review:
    types: [submitted]
jobs:
  run-deploy:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # So we can diff with base branch

      - name: Check for folder changes
        id: check_changes
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD)
          echo "$CHANGED_FILES"
          echo "$CHANGED_FILES" | grep 'sync-azure-blob-to-s3' && echo "changed=true" >> $GITHUB_OUTPUT || echo "changed=false" >> $GITHUB_OUTPUT

      - name: Set up Node.js
        if: steps.check_changes.outputs.changed == 'true'
        uses: ./.github/actions/setup-node

      - name: Set up Azure CLI
        if: steps.check_changes.outputs.changed == 'true'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Run deploy script
        if: steps.check_changes.outputs.changed == 'true'
        run: ./common/devops/scripts/sync-azure-blob-to-s3/deploy.sh
