name: Run on Changes to src Directory

on:
  push:
    branches:
      - main
    paths:
      - 'common/devops/scripts/my-deploy-script1/**' # Change this to your target directory

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run a script
        run: echo "Changes detected in src/, running job..."
