name: E2E tests
on:
  workflow_dispatch:
    inputs:
      prNumber:
        type: number
        description: 'The number of the PR you would like to test'
        required: false
      environment:
        type: environment
        description: 'The environment to run against: production, staging, pr'
        required: true
        default: 'pr'
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'The environment to run against: production, staging, pr'
        required: true
        default: 'pr'
jobs:
  playwright-pr-tests:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    steps:
      - name: Install packages
        uses: actions/checkout@v4
      - run: echo "Hello from ${{ inputs.environment }}"
      - run: cat version.txt
      - run: |
          echo "Running shard ${{ matrix.shard }}"
          RANDOM_NUM=$((RANDOM % 2))
          echo "Random number: $RANDOM_NUM"
          if [ "$RANDOM_NUM" -eq 0 ]; then
            echo "💥 Simulating failure in shard ${{ matrix.shard }}"
            exit 1
          else
            echo "✅ Shard ${{ matrix.shard }} passed"
          fi  
  merge-reports:
    needs: [playwright-pr-tests]
    runs-on: ubuntu-24.04
    if: always()
    steps:
      - run: echo "hello world ${{ inputs.prNumber }}"
      - run: echo "runid ${{ github.run_id }}"
