name: E2E tests
on:
  workflow_dispatch:
    inputs:
      prNumber:
        type: number
        description: 'The number of the PR you would like to test'
        required: false
      environment:
        type: environment
        description: 'The environment to run against: production, staging, pr'
        required: true
        default: 'pr'
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'The environment to run against: production, staging, pr'
        required: true
        default: 'pr'
jobs:
  playwright-pr-tests:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Install packages
        uses: actions/checkout@v4
      - run: echo "Hello from ${{ inputs.environment }}"
      - run: cat version.txt
  merge-reports:
    needs: [playwright-pr-tests]
    runs-on: ubuntu-24.04
    steps:
      - run: echo "hello world ${{ inputs.prNumber ?? null }}"
