name: Release
on:
  workflow_dispatch:
jobs:
  trigger-tests:
    uses: ./.github/workflows/pr-e2e.yml
    with: 
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
